# Generated by Django 4.1.3 on 2023-12-09 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tunaapi', '0005_song_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='artists', to='tunaapi.genre'),
        ),
    ]
